---
title: "PS811 Portfolio"
author: "Monica Komer"
output:
  html_document: 
    toc: true ## table of contents
    code_folding: hide
---
```{r setup, include=FALSE}
## Defaults for R chunks
knitr::opts_chunk$set(echo = TRUE, ## echo = TRUE means code will show
                      warning=FALSE, ## supress warnings and messages from R
                      message=FALSE,
                      fig.path='Figs/', ## where to save figures
                      fig.height = 3, ## default figure size (can differ in each chunk)
                      fig.width = 3)

## Add any R packages you require. 
## Here are some we will use in 811:
requires <- c("tidyverse", ## tidyverse includes dplyr and ggplot2
              "magrittr",
              "foreign",
              "readstata13",
              "here")

## Install any you don't have
to_install <- c(requires %in% rownames(installed.packages()) == FALSE)
install.packages(c(requires[to_install], "NA"), repos = "https://cloud.r-project.org/" )

## Load all required R packages
library(tidyverse)
library(ggplot2); theme_set(theme_minimal())
library(magrittr)
library(here)
```
<!-- The above header sets everything up. -->





<!-- Replace the below with bit about you. -->
### Research Interests
The overarching focus of my research is on the causes and consequences of women’s representation with a particular focus on the Middle East and North Africa. More specifically, I am interested in studying how (and which) women gain leadership positions in political parties and the effect of women’s presence on citizen’s attitudes and behaviors. 

### Questions I hope to answer
Which women gain leadership positions in secular and religious parties? What determines which women run, where (i.e. district location) they run, and their position on party lists?

Do female politicians interact with constituents differently than their male colleagues? Is this conditional on party affiliation or quota type? Are citizens more loyal to regimes that enact gender quotas? Are women more interested in politics when represented by a woman instead of a male?

---

### Methods
Various regression models including hierarchical models, survey experiments, text analysis, and qualitative methods (primarily interviews and focus groups). 

---

### Relevent data

- Arab Barometer ( [data](http://www.arabbarometer.org/survey-data/) )

- World Values Survey ( [data](http://www.worldvaluessurvey.org/WVSContents.jsp) )

- Afro Barometer ( [data](http://www.afrobarometer.org/data) )

- Quota Adoption and Reform over Time (QAROT) dataset ( [data](https://www.openicpsr.org/openicpsr/project/100918/version/V1/view) )

- Tunisia Election Data (results by district available [here](http://tunisiaelectiondata.com/) )






